# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basket.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

conn = sqlite3.connect("db.db")


class Ui_MainWindow(object):
    def __init__(self, basket):
        self.cur = conn.cursor()
        self.data = self.cur.execute("SELECT * FROM products;")
        self.res = self.data.fetchall()
        self.basket = basket
        self.basketLayout = []

    def setupUi(self, MainWindow):
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(414, 736)
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setStyleSheet("#MainWidget{\n"
                                             "    background-color:rgb(63, 61, 60)\n"
                                             "}\n"
                                             "\n"
                                             "QLabel{\n"
                                             "    color:rgb(255, 255, 255);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton{\n"
                                             "    color:rgb(255, 255, 255);\n"
                                             "    background-color: rgba(255, 255, 255, 20);\n"
                                             "}")
            self.centralwidget.setObjectName("centralwidget")
            self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
            self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.MainWidget = QtWidgets.QWidget(self.centralwidget)
            self.MainWidget.setStyleSheet("")
            self.MainWidget.setObjectName("MainWidget")
            self.verticalLayout = QtWidgets.QVBoxLayout(self.MainWidget)
            self.verticalLayout.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout.setSpacing(10)
            self.verticalLayout.setObjectName("verticalLayout")
            self.TitleWidget = QtWidgets.QWidget(self.MainWidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.TitleWidget.sizePolicy().hasHeightForWidth())
            self.TitleWidget.setSizePolicy(sizePolicy)
            self.TitleWidget.setMinimumSize(QtCore.QSize(0, 60))
            self.TitleWidget.setStyleSheet("QPushButton {\n"
                                           "    border-radius: 20px;\n"
                                           "}\n"
                                           "")
            self.TitleWidget.setObjectName("TitleWidget")
            self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TitleWidget)
            self.horizontalLayout_2.setObjectName("horizontalLayout_2")
            self.label_3 = QtWidgets.QLabel(self.TitleWidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
            self.label_3.setSizePolicy(sizePolicy)
            self.label_3.setMinimumSize(QtCore.QSize(48, 44))
            self.label_3.setMaximumSize(QtCore.QSize(48, 44))
            font = QtGui.QFont()
            font.setPointSize(14)
            self.label_3.setFont(font)
            self.label_3.setText("")
            self.label_3.setTextFormat(QtCore.Qt.AutoText)
            self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/burger-svgrepo-com.png"))
            self.label_3.setScaledContents(True)
            self.label_3.setAlignment(QtCore.Qt.AlignCenter)
            self.label_3.setObjectName("label_3")
            self.horizontalLayout_2.addWidget(self.label_3)
            self.label = QtWidgets.QLabel(self.TitleWidget)
            font = QtGui.QFont()
            font.setPointSize(12)
            font.setBold(True)
            font.setWeight(75)
            self.label.setFont(font)
            self.label.setAlignment(QtCore.Qt.AlignCenter)
            self.label.setObjectName("label")
            self.horizontalLayout_2.addWidget(self.label)
            self.pushButton_4 = QtWidgets.QPushButton(self.TitleWidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
            self.pushButton_4.setSizePolicy(sizePolicy)
            self.pushButton_4.setMinimumSize(QtCore.QSize(0, 0))
            self.pushButton_4.setMaximumSize(QtCore.QSize(42, 42))
            self.pushButton_4.setStyleSheet("")
            self.pushButton_4.setText("")
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap(":/icons/icons/1564505_close_delete_exit_remove_icon.png"), QtGui.QIcon.Normal,
                           QtGui.QIcon.Off)
            self.pushButton_4.setIcon(icon)
            self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
            self.pushButton_4.setObjectName("pushButton_4")
            self.horizontalLayout_2.addWidget(self.pushButton_4)
            self.verticalLayout.addWidget(self.TitleWidget)
            self.Main = QtWidgets.QWidget(self.MainWidget)
            self.Main.setObjectName("Main")
            self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Main)
            self.verticalLayout_2.setContentsMargins(12, 0, 12, 0)
            self.verticalLayout_2.setSpacing(0)
            self.verticalLayout_2.setObjectName("verticalLayout_2")
            spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
            self.verticalLayout_2.addItem(spacerItem)
            self.ProductListWidget = QtWidgets.QWidget(self.Main)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.ProductListWidget.sizePolicy().hasHeightForWidth())
            self.ProductListWidget.setSizePolicy(sizePolicy)
            self.ProductListWidget.setObjectName("ProductListWidget")
            self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ProductListWidget)
            self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout_3.setSpacing(10)
            self.verticalLayout_3.setObjectName("verticalLayout_3")
            self.product = QtWidgets.QLabel(self.ProductListWidget)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.product.sizePolicy().hasHeightForWidth())
            self.product.setSizePolicy(sizePolicy)
            font = QtGui.QFont()
            font.setPointSize(18)
            font.setBold(True)
            font.setWeight(75)
            self.product.setFont(font)
            self.product.setObjectName("product")
            self.verticalLayout_3.addWidget(self.product)
            self.verticalLayout_2.addWidget(self.ProductListWidget)
            spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
            self.verticalLayout_2.addItem(spacerItem1)
            self.Widget = QtWidgets.QWidget(self.Main)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.Widget.sizePolicy().hasHeightForWidth())
            self.Widget.setSizePolicy(sizePolicy)
            self.Widget.setMinimumSize(QtCore.QSize(0, 0))
            self.Widget.setObjectName("Widget")
            self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Widget)
            self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout_4.setSpacing(0)
            self.verticalLayout_4.setObjectName("verticalLayout_4")
            self.pushButton = QtWidgets.QPushButton(self.Widget)
            self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
            self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
            self.pushButton.setObjectName("pushButton")
            self.verticalLayout_4.addWidget(self.pushButton)
            self.verticalLayout_2.addWidget(self.Widget)
            spacerItem2 = QtWidgets.QSpacerItem(20, 140, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
            self.verticalLayout_2.addItem(spacerItem2)
            self.verticalLayout.addWidget(self.Main)
            self.horizontalLayout.addWidget(self.MainWidget)
            MainWindow.setCentralWidget(self.centralwidget)

            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

            self.Update()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BurgerBurger"))
        self.product.setText(_translate("MainWindow", "aliksfnafnaf"))
        self.pushButton.setText(_translate("MainWindow", "Купить"))

    def Update(self):
        for i in reversed(range(self.verticalLayout_3.count())):
            self.verticalLayout_3.itemAt(i).widget().setParent(None)
        for i in range(len(self.basket)):
            for product in self.res:
                if self.basket[i] == product[1]:
                        self.basketLayout.append(QtWidgets.QPushButton(self.ProductListWidget))

                        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
                        sizePolicy.setHorizontalStretch(0)
                        sizePolicy.setVerticalStretch(0)
                        self.basketLayout[i].setSizePolicy(sizePolicy)

                        font = QtGui.QFont()
                        font.setPointSize(16)
                        font.setBold(True)
                        font.setWeight(75)
                        self.basketLayout[i].setFont(font)

                        icon1 = QtGui.QIcon()
                        icon1.addPixmap(QtGui.QPixmap(product[3]), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                        self.basketLayout[i].setIcon(icon1)
                        self.basketLayout[i].setIconSize(QtCore.QSize(48, 48))

                        self.basketLayout[i].setObjectName(product[1])
                        self.basketLayout[i].setText(product[1] + " - " + str(product[2]) + "руб.")
                        self.basketLayout[i].setStyleSheet("text-align: left; border-radius: 5px")
                        self.verticalLayout_3.addWidget(self.basketLayout[i])
                        break
import resources_rc
